apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: younicorns
  description: The Younicorns organization
  links:
    - url: http://younicorns.io
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: Younicorns
    email: contact@younicorns.io
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Younicorns Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml

