apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: younicorns
  description: Younicorns tech team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: contact@younicorns.io
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: gilles.dansou
spec:
  profile:
    # Intentional no displayName for testing
    displayName: Gilles Dansou
    email: gilles@younicorns.io
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [younicorns]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jonathan.horyn
spec:
  profile:
    displayName: Jonathan Horyn
    email: jonathan@younicorns.io
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [younicorns]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [team-a]
